export const renderInitialValues = (student, sacraments,classId) => {
    if (student && student._id) {
    if (sacraments) {
      return {
        holyName: student.holyName || "",
        name: student.name || "",
        phone: student.phone || "",
        fatherName: student.fatherName || "",
        motherName: student.motherName || "",
        address: student.address || "",
        gender: student.gender || "Nam",
        birthDay: student.birthDay || "",
        idClass: classId || "",
        baptismDay: student.baptismDay || "",
        familyId: sacraments?.familyId || "",
        baptismName: "Rửa tội",
        baptismDate: sacraments.sacrament[0].date || "",
        baptismMinister: sacraments.sacrament[0]?.pastor || "",
        baptismChurch: sacraments.sacrament[0]?.parish || "",
        baptismNumber: sacraments.sacrament[0]?.number || "",
        baptismSponsor: sacraments.sacrament[0]?.sponsor || "",
        baptismDiocese: sacraments.sacrament[0]?.diocese || "",

        confirmationName: "Thêm sức",
        confirmationDate: sacraments.sacrament[2]?.date || "",
        confirmationMinister:
          sacraments.sacrament[2]?.pastor || "",
        confirmationChurch: sacraments.sacrament[2]?.parish || "",
        confirmationNumber: sacraments.sacrament[2]?.number || "",
        confirmationSponsor: sacraments.sacrament[2]?.sponsor || "",
        confirmationDiocese: sacraments.sacrament[2]?.diocese || "",

        communionName: "Xưng tội",
        communionDate: sacraments.sacrament[1]?.date || "",
        communionMinister: sacraments.sacrament[1]?.pastor || "",
        communionChurch: sacraments.sacrament[1]?.parish || "",
        communionNumber: sacraments.sacrament[1]?.number || "",
        communionSponsor: sacraments.sacrament[1]?.sponsor || "",
        communionDiocese: sacraments.sacrament[1]?.diocese || "",
      };
    } else {
      return {
        holyName: student.holyName || "",
        name: student.name || "",
        phone: student.phone || "",
        fatherName: student.fatherName || "",
        motherName: student.motherName || "",
        address: student.address || "",
        gender: student.gender || "Nam",
        birthDay: student.birthDay || "",
        idClass: classId || "",
        baptismDay: student.baptismDay || "",
        familyId: sacraments?.familyId || "",
        baptismName: "Rửa tội",
        baptismDate: "",
        baptismMinister: "",
        baptismChurch: "",
        baptismNumber: "",
        baptismSponsor: "",
        baptismDiocese: "",
        confirmationName: "Thêm sưc",
        confirmationDate: "",
        confirmationMinister: "",
        confirmationChurch: "",
        confirmationNumber: "",
        confirmationSponsor: "",
        confirmationDiocese: "",

        communionName: "Xưng tội",
        communionDate: "",
        communionMinister: "",
        communionChurch: "",
        communionNumber: "",
        communionSponsor: "",
        communionDiocese: "",
      };
    }
  } else {
    return {
      name: "",
      phone: "",
      fatherName: "",
      motherName: "",
      address: "",
      gender: "Nam",
      birthDay: "",
      idClass: "",
      baptismDay: "",
      holyName: "",
      familyId: "",
      baptismName: "Rửa tội",
      baptismDate: "",
      baptismMinister: "",
      baptismChurch: "",
      baptismNumber: "",
      baptismSponsor: "",
      baptismDiocese: "",

      confirmationName: "Thêm sức",
      confirmationDate: "",
      confirmationMinister: "",
      confirmationChurch: "",
      confirmationNumber: "",
      confirmationSponsor: "",
      confirmationDiocese: "",

      communionName: "Xưng tội",
      communionDate: "",
      communionMinister: "",
      communionChurch: "",
      communionNumber: "",
      communionSponsor: "",
      communionDiocese: "",
    };
  }
};
